import React, { useState } from 'react';
import { FileCode, Copy, Download, ChevronDown, ChevronUp, Check } from 'lucide-react';
import type { CertificateData } from '../types/certificate';

interface PemViewerProps {
  cert: CertificateData;
  darkMode: boolean;
}

export const PemViewer: React.FC<PemViewerProps> = ({ cert, darkMode }) => {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copiedReport, setCopiedReport] = useState(false);

  const pemLines = cert.pem.split('\n');
  const visiblePem = expanded ? cert.pem : pemLines.slice(0, 6).join('\n') + '\n...';

  const handleCopy = async () => {
    await navigator.clipboard.writeText(cert.pem);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([cert.pem], { type: 'application/x-pem-file' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${cert.domain}.crt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateReport = () => {
    return `SSLSpy Certificate Report
Generated: ${new Date().toISOString()}
Domain: ${cert.domain}
${'='.repeat(60)}

CERTIFICATE SUMMARY
Status: ${cert.status.toUpperCase()}
Subject: CN=${cert.subject.cn}${cert.subject.o ? `, O=${cert.subject.o}` : ''}
Issuer: CN=${cert.issuer.cn}${cert.issuer.o ? `, O=${cert.issuer.o}` : ''}
Valid From: ${cert.validFrom}
Valid To: ${cert.validTo}
Days Remaining: ${cert.daysRemaining}

SECURITY DETAILS
Public Key: ${cert.publicKey.algorithm} ${cert.publicKey.keySize}-bit
Signature: ${cert.signatureAlgorithm}
TLS Version: ${cert.tlsVersion}
Forward Secrecy: ${cert.forwardSecrecy ? 'Yes' : 'No'}
Wildcard: ${cert.isWildcard ? 'Yes' : 'No'}
Self-Signed: ${cert.isSelfSigned ? 'Yes' : 'No'}

SANs: ${cert.san.join(', ')}

SECURITY SCORE: ${cert.score}/100 (Grade ${cert.grade})
${cert.scoreBreakdown.map(i => `  ${i.positive ? '+' : ''}${i.points}: ${i.label}`).join('\n')}

FINGERPRINTS
SHA-256: ${cert.fingerprint.sha256}
SHA-1:   ${cert.fingerprint.sha1}
Serial:  ${cert.serialNumber}

${'='.repeat(60)}
This report is for informational purposes only.
Generated by SSLSpy - SSL/TLS Certificate Inspector`;
  };

  const handleCopyReport = async () => {
    await navigator.clipboard.writeText(generateReport());
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2000);
  };

  const handleDownloadReport = () => {
    const blob = new Blob([generateReport()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${cert.domain}-sslspy-report.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJson = () => {
    const { pem: _, ...certWithoutPem } = cert;
    const json = JSON.stringify({ ...certWithoutPem, generatedAt: new Date().toISOString() }, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${cert.domain}-sslspy.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className={`rounded-2xl border overflow-hidden ${darkMode ? 'bg-slate-800/60 border-slate-700/60' : 'bg-white border-slate-200'}`}>
      <div className={`px-5 py-3.5 border-b flex items-center gap-2 ${darkMode ? 'border-slate-700/60' : 'border-slate-100'}`}>
        <FileCode className="w-4 h-4 text-cyan-500" />
        <h2 className={`text-xs font-bold uppercase tracking-widest ${darkMode ? 'text-slate-300' : 'text-slate-600'}`}>
          Full Certificate (PEM)
        </h2>
      </div>

      <div className="p-5 space-y-4">
        {/* PEM Block */}
        <div className={`relative rounded-xl overflow-hidden border ${darkMode ? 'bg-slate-950 border-slate-700' : 'bg-slate-900 border-slate-700'}`}>
          <div className={`flex items-center justify-between px-4 py-2 border-b border-slate-700/50`}>
            <span className="text-xs font-mono text-slate-400">certificate.pem</span>
            <div className="flex items-center gap-2">
              <div className="w-2.5 h-2.5 rounded-full bg-red-500/60" />
              <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/60" />
              <div className="w-2.5 h-2.5 rounded-full bg-green-500/60" />
            </div>
          </div>
          <pre className="p-4 text-xs font-mono text-green-400 leading-relaxed overflow-x-auto max-h-48 overflow-y-auto whitespace-pre-wrap break-all">
            {visiblePem}
          </pre>
          <button
            onClick={() => setExpanded(!expanded)}
            className="w-full flex items-center justify-center gap-2 py-2 border-t border-slate-700/50 text-xs text-slate-400 hover:text-slate-200 hover:bg-slate-800/50 transition-colors"
          >
            {expanded ? <><ChevronUp className="w-3 h-3" /> Show Less</> : <><ChevronDown className="w-3 h-3" /> Show Full Certificate</>}
          </button>
        </div>

        {/* PEM Actions */}
        <div className="flex flex-wrap gap-2">
          <button
            onClick={handleCopy}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium transition-all ${
              copied
                ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                : (darkMode ? 'bg-slate-700 text-slate-300 hover:bg-slate-600 border border-slate-600' : 'bg-slate-100 text-slate-700 hover:bg-slate-200 border border-slate-200')
            }`}
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied!' : 'Copy Certificate'}
          </button>
          <button
            onClick={handleDownload}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium transition-all ${darkMode ? 'bg-slate-700 text-slate-300 hover:bg-slate-600 border border-slate-600' : 'bg-slate-100 text-slate-700 hover:bg-slate-200 border border-slate-200'}`}
          >
            <Download className="w-4 h-4" />
            Download .crt
          </button>
        </div>

        {/* Report Export */}
        <div className={`pt-4 border-t ${darkMode ? 'border-slate-700/60' : 'border-slate-100'}`}>
          <div className={`text-xs font-semibold uppercase tracking-wider mb-3 ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>
            Export Report
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              onClick={handleCopyReport}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium transition-all ${
                copiedReport
                  ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                  : 'bg-gradient-to-r from-cyan-500/10 to-blue-600/10 text-cyan-500 border border-cyan-500/20 hover:from-cyan-500/20 hover:to-blue-600/20'
              }`}
            >
              {copiedReport ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {copiedReport ? 'Copied!' : 'Copy Report'}
            </button>
            <button
              onClick={handleDownloadReport}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium transition-all bg-gradient-to-r from-cyan-500/10 to-blue-600/10 text-cyan-500 border border-cyan-500/20 hover:from-cyan-500/20 hover:to-blue-600/20`}
            >
              <Download className="w-4 h-4" />
              Report (.txt)
            </button>
            <button
              onClick={handleDownloadJson}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium transition-all bg-gradient-to-r from-purple-500/10 to-blue-600/10 text-purple-400 border border-purple-500/20 hover:from-purple-500/20 hover:to-blue-600/20`}
            >
              <Download className="w-4 h-4" />
              JSON Export
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
